// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/moreal/jandibat.org/apps/api/internal/graphql/scalar"
)

// Mutation results carry typed data and validation errors; transport failures use GraphQL errors.
type MutationPayload interface {
	IsMutationPayload()
	GetErrors() []*MutationError
}

// A durable entity with an opaque, globally unique identity.
type Node interface {
	IsNode()
	GetID() string
}

// A value object; activity days are not Relay Nodes.
type ActivityDay struct {
	Date    scalar.Date      `json:"date"`
	Count   scalar.Long      `json:"count"`
	Level   int              `json:"level"`
	Entries []*ActivityEntry `json:"entries"`
}

type ActivityEntry struct {
	EnvironmentID string                   `json:"environmentID"`
	Action        string                   `json:"action"`
	MetricName    string                   `json:"metricName"`
	MetricValue   scalar.Long              `json:"metricValue"`
	Metadata      []*ActivityMetadataEntry `json:"metadata"`
}

type ActivityEnvironment struct {
	ID       string                   `json:"id"`
	Key      string                   `json:"key"`
	Name     string                   `json:"name"`
	Scope    string                   `json:"scope"`
	Metadata []*ActivityMetadataEntry `json:"metadata"`
}

type ActivityMetadataEntry struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// A complete authorized projection for static consumers.
type ActivitySnapshot struct {
	Subject       *Subject               `json:"subject"`
	Range         *DateRange             `json:"range"`
	Days          []*ActivityDay         `json:"days"`
	Environments  []*ActivityEnvironment `json:"environments"`
	Total         scalar.Long            `json:"total"`
	LongestStreak int                    `json:"longestStreak"`
	GeneratedAt   scalar.DateTime        `json:"generatedAt"`
	// Null only when this scoped range has never incorporated activity.
	DataUpdatedAt *scalar.DateTime `json:"dataUpdatedAt,omitempty"`
	Revision      string           `json:"revision"`
}

type CustomProvider struct {
	ID string `json:"id"`
}

func (CustomProvider) IsNode()            {}
func (this CustomProvider) GetID() string { return this.ID }

type DateRange struct {
	From scalar.Date `json:"from"`
	To   scalar.Date `json:"to"`
}

type DateRangeInput struct {
	From scalar.Date `json:"from"`
	To   scalar.Date `json:"to"`
}

// Mutation root; domain mutations are added after their authorization tests.
type Mutation struct {
}

// A stable domain validation failure returned inside mutation payloads.
type MutationError struct {
	Code    string  `json:"code"`
	Message string  `json:"message"`
	Field   *string `json:"field,omitempty"`
}

// Standard forward-only Relay connection page information.
type PageInfo struct {
	HasNextPage     bool           `json:"hasNextPage"`
	HasPreviousPage bool           `json:"hasPreviousPage"`
	StartCursor     *scalar.Cursor `json:"startCursor,omitempty"`
	EndCursor       *scalar.Cursor `json:"endCursor,omitempty"`
}

type ProviderConnection struct {
	ID string `json:"id"`
	// Forward page; first: 1..100, default 25.
	SyncJobs *SyncJobConnection `json:"syncJobs,omitempty"`
}

func (ProviderConnection) IsNode()            {}
func (this ProviderConnection) GetID() string { return this.ID }

// Root of the domain API. Domain fields are added with resolver authorization.
type Query struct {
}

type Session struct {
	ID         string           `json:"id"`
	CreatedAt  scalar.DateTime  `json:"createdAt"`
	ExpiresAt  scalar.DateTime  `json:"expiresAt"`
	RevokedAt  *scalar.DateTime `json:"revokedAt,omitempty"`
	LastSeenAt *scalar.DateTime `json:"lastSeenAt,omitempty"`
	IPAddress  *string          `json:"ipAddress,omitempty"`
	UserAgent  *string          `json:"userAgent,omitempty"`
}

func (Session) IsNode()            {}
func (this Session) GetID() string { return this.ID }

type SessionConnection struct {
	Edges    []*SessionEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type SessionEdge struct {
	Cursor scalar.Cursor `json:"cursor"`
	Node   *Session      `json:"node"`
}

type Subject struct {
	ID string `json:"id"`
	// A bounded, static projection; non-owners see only public activity.
	ActivitySnapshot *ActivitySnapshot `json:"activitySnapshot"`
}

func (Subject) IsNode()            {}
func (this Subject) GetID() string { return this.ID }

type SyncJob struct {
	ID        string          `json:"id"`
	Status    string          `json:"status"`
	Attempt   int             `json:"attempt"`
	CreatedAt scalar.DateTime `json:"createdAt"`
	UpdatedAt scalar.DateTime `json:"updatedAt"`
}

func (SyncJob) IsNode()            {}
func (this SyncJob) GetID() string { return this.ID }

type SyncJobConnection struct {
	Edges    []*SyncJobEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type SyncJobEdge struct {
	Cursor scalar.Cursor `json:"cursor"`
	Node   *SyncJob      `json:"node"`
}

type UserProfile struct {
	ID              string           `json:"id"`
	PrimaryEmail    string           `json:"primaryEmail"`
	Status          string           `json:"status"`
	EmailVerifiedAt *scalar.DateTime `json:"emailVerifiedAt,omitempty"`
	CreatedAt       scalar.DateTime  `json:"createdAt"`
	UpdatedAt       scalar.DateTime  `json:"updatedAt"`
}

// The viewer is a scoped value object, not a globally addressable Node.
type Viewer struct {
	User *UserProfile `json:"user"`
	// Forward page; first: 1..100, default 25.
	Sessions *SessionConnection `json:"sessions"`
}
