// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Mutation results carry typed data and validation errors; transport failures use GraphQL errors.
type MutationPayload interface {
	IsMutationPayload()
	GetErrors() []*MutationError
}

// A durable entity with an opaque, globally unique identity.
type Node interface {
	IsNode()
	GetID() string
}

type CustomProvider struct {
	ID string `json:"id"`
}

func (CustomProvider) IsNode()            {}
func (this CustomProvider) GetID() string { return this.ID }

// Mutation root; domain mutations are added after their authorization tests.
type Mutation struct {
}

// A stable domain validation failure returned inside mutation payloads.
type MutationError struct {
	Code    string  `json:"code"`
	Message string  `json:"message"`
	Field   *string `json:"field,omitempty"`
}

type ProviderConnection struct {
	ID string `json:"id"`
}

func (ProviderConnection) IsNode()            {}
func (this ProviderConnection) GetID() string { return this.ID }

// Root of the domain API. Domain fields are added with resolver authorization.
type Query struct {
}

type Session struct {
	ID string `json:"id"`
}

func (Session) IsNode()            {}
func (this Session) GetID() string { return this.ID }

type Subject struct {
	ID string `json:"id"`
}

func (Subject) IsNode()            {}
func (this Subject) GetID() string { return this.ID }

type SyncJob struct {
	ID string `json:"id"`
}

func (SyncJob) IsNode()            {}
func (this SyncJob) GetID() string { return this.ID }
