// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Mutation results carry typed data and validation errors; transport failures use GraphQL errors.
type MutationPayload interface {
	IsMutationPayload()
	GetErrors() []*MutationError
}

// A durable entity with an opaque, globally unique identity.
type Node interface {
	IsNode()
	GetID() string
}

// Mutation root; domain mutations are added after their authorization tests.
type Mutation struct {
}

// A stable domain validation failure returned inside mutation payloads.
type MutationError struct {
	Code    string  `json:"code"`
	Message string  `json:"message"`
	Field   *string `json:"field,omitempty"`
}

// Root of the domain API. Domain fields are added with resolver authorization.
type Query struct {
}
